version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/test
      JDBC_USER: test
      JDBC_PASSWORD: secret

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
