server:
  port: ${PORT:80}

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/test}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD:}
