server:
  error:
    include-stacktrace: never
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/db}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD:}
