name: Kotlin CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Lint Kotlin code
        run: ./gradlew ktlintCheck

      - name: Test Kotlin code
        run: ./gradlew strongTest

  build:
    runs-on: ubuntu-latest
    needs:
      - lint-and-tests

    steps:
      # Шаг 2: Сборка Docker образа и пуш в Docker Hub
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ikuyotagan/to-do-list:$GITHUB_SHA -f docker/Dockerfile .

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: docker push ikuyotagan/to-do-list:$GITHUB_SHA
