name: Kotlin CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Lint Kotlin code
        run: ./gradlew ktlintCheck

      # Шаг 2: Сборка Docker образа и пуш в Docker Hub
      - name: Build Docker image
        run: docker build -t yourusername/yourrepository:$GITHUB_SHA .

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: docker push yourusername/yourrepository:$GITHUB_SHA

      # Шаг 3: Отправка уведомления на почту
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions build ${{ github.run_id }} completed
          # Дополнительные настройки для почтового клиента
          from: Your Name <your-email@gmail.com>
          to: recipient-email@gmail.com
          body: Build ${{ github.run_id }} completed successfully!
          secure: true
